title: Virtual Organ Workshop
lang: en
description: A companion website to the weekly organ workshops held over Zoom by Elder Cranford.

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
